/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import DAO.ProductoDAOImplements;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import productos.Arrayp;
import productos.Producto;
import proyecto.*;

/**
 *
 * @author a21cirosc
 */
public class JFrame_index extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame_index() {
        initComponents();
        jButton_desconectar.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    public Image getIconImage() {
        Image imaxe
                = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imaxes/Horario.png"));
        return imaxe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Index = new javax.swing.JPanel();
        logo_grande = new javax.swing.JLabel();
        JLabel_perfil = new javax.swing.JLabel();
        jTextField_usuario = new javax.swing.JTextField();
        jLabel_usuario = new javax.swing.JLabel();
        jLabel_password = new javax.swing.JLabel();
        jTextField_password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_departamentos = new javax.swing.JLabel();
        jButton_buscar_libros = new javax.swing.JButton();
        jLabel_total_texto = new javax.swing.JLabel();
        jLabel_output = new javax.swing.JLabel();
        jLabel_total1 = new javax.swing.JLabel();
        jComboBox_libros = new javax.swing.JComboBox<>();
        jComboBox_mat_oficina = new javax.swing.JComboBox<>();
        JPanel_cesta_fondo_6 = new javax.swing.JPanel();
        jLabel_img_producto_seleccionado4 = new javax.swing.JLabel();
        jLabel_info_producto_seleccionado4 = new javax.swing.JLabel();
        jButton_add_cesta4 = new javax.swing.JButton();
        jLabel_precio_producto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_cantidad_productos = new javax.swing.JTextField();
        jLabel_nombre_producto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_info_producto = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_otros = new javax.swing.JComboBox<>();
        jLabel_departamentos1 = new javax.swing.JLabel();
        jLabel_departamentos2 = new javax.swing.JLabel();
        jLabel_departamentos3 = new javax.swing.JLabel();
        jButton_borrar_cesta = new javax.swing.JButton();
        jButton_buscar_mat_oficina = new javax.swing.JButton();
        jButton_buscar_otros = new javax.swing.JButton();
        jButton_comprar = new javax.swing.JButton();
        jButton_mosrtar_cesta = new javax.swing.JButton();
        jButton_desconectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("prinicipal");
        setIconImage(getIconImage());

        jPanel_Index.setBackground(new java.awt.Color(212, 245, 245));
        jPanel_Index.setName(""); // NOI18N
        jPanel_Index.setPreferredSize(new java.awt.Dimension(750, 500));

        logo_grande.setForeground(new java.awt.Color(90, 91, 92));
        logo_grande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imaxes/gfdsghsfdhgfhdf.png"))); // NOI18N

        JLabel_perfil.setForeground(new java.awt.Color(90, 91, 92));
        JLabel_perfil.setText("Perfil");

        jTextField_usuario.setBackground(new java.awt.Color(90, 91, 94));
        jTextField_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usuarioActionPerformed(evt);
            }
        });

        jLabel_usuario.setForeground(new java.awt.Color(90, 91, 92));
        jLabel_usuario.setText("Usuario");

        jLabel_password.setForeground(new java.awt.Color(90, 91, 92));
        jLabel_password.setText("Contraseña");

        jTextField_password.setBackground(new java.awt.Color(90, 91, 94));
        jTextField_password.setText("jPasswordField1");

        jButton1.setBackground(new java.awt.Color(140, 154, 158));
        jButton1.setForeground(new java.awt.Color(250, 250, 255));
        jButton1.setText("Conectarse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login(evt);
            }
        });

        jLabel_departamentos.setForeground(new java.awt.Color(90, 91, 92));
        jLabel_departamentos.setText("Departamentos:");

        jButton_buscar_libros.setBackground(new java.awt.Color(140, 154, 158));
        jButton_buscar_libros.setForeground(new java.awt.Color(250, 250, 255));
        jButton_buscar_libros.setText("Buscar");
        jButton_buscar_libros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_librosMouseEntered(evt);
            }
        });
        jButton_buscar_libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscar_librosActionPerformed(evt);
            }
        });

        jLabel_total_texto.setForeground(new java.awt.Color(90, 91, 92));
        jLabel_total_texto.setText("TOTAL:");

        jLabel_output.setForeground(new java.awt.Color(90, 91, 92));
        jLabel_output.setText("0");

        jLabel_total1.setForeground(new java.awt.Color(90, 91, 92));
        jLabel_total1.setText("€");

        jComboBox_libros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[nombre]", "FARIÑA", "LA LADRONA DE HUESOS", "LA ÚLTIMA MISIÓN DE GWENDY", "ROMA SOY YO", "EL LIBRO NEGRO DE LAS HORAS", "LA TORRE Y LA ISLA", "UN MUNDO FELIZ", "ORGULLO Y PREJUICIO", "EL EXTRANJERO", "1984", "LA LADRONA DE LIBROS", "FAHRENHEIT 451", "EL PRINCIPITO", "MARINA", "ENSAYO SOBRE LA CEGUERA" }));
        jComboBox_libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_librosActionPerformed(evt);
            }
        });

        jComboBox_mat_oficina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[nombre]", "BOLÍGRAFO G2", "AGENDA 2022", "ARCHIVADOR", "CARPETA", "LÁPIZ DE GRAFITO", "GOMA DE BORRAR", "REGLA", "CUADERNO", "PORTAMINAS", "BOLÍGRAFOS DE COLORES" }));

        JPanel_cesta_fondo_6.setBackground(new java.awt.Color(147, 183, 179));

        jLabel_img_producto_seleccionado4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_img_producto_seleccionado4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imaxes/Libruhria_Logo.png"))); // NOI18N

        jLabel_info_producto_seleccionado4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel_info_producto_seleccionado4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_info_producto_seleccionado4.setText("Info Producto:");

        jButton_add_cesta4.setText("Añadir a cesta");
        jButton_add_cesta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_cesta4ActionPerformed(evt);
            }
        });

        jLabel_precio_producto.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_precio_producto.setText("0.0");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Precio:");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Cantidad:");

        jTextField_cantidad_productos.setText("0");
        jTextField_cantidad_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cantidad_productosActionPerformed(evt);
            }
        });

        jLabel_nombre_producto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel_nombre_producto.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_nombre_producto.setText("[nombre]");

        jTextArea_info_producto.setEditable(false);
        jTextArea_info_producto.setColumns(20);
        jTextArea_info_producto.setRows(5);
        jScrollPane1.setViewportView(jTextArea_info_producto);

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("€");

        javax.swing.GroupLayout JPanel_cesta_fondo_6Layout = new javax.swing.GroupLayout(JPanel_cesta_fondo_6);
        JPanel_cesta_fondo_6.setLayout(JPanel_cesta_fondo_6Layout);
        JPanel_cesta_fondo_6Layout.setHorizontalGroup(
            JPanel_cesta_fondo_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_cesta_fondo_6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(JPanel_cesta_fondo_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_nombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_img_producto_seleccionado4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(JPanel_cesta_fondo_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel_cesta_fondo_6Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(JPanel_cesta_fondo_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_add_cesta4)
                            .addGroup(JPanel_cesta_fondo_6Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_cantidad_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPanel_cesta_fondo_6Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_precio_producto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)))
                        .addGap(21, 21, 21))
                    .addGroup(JPanel_cesta_fondo_6Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel_info_producto_seleccionado4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        JPanel_cesta_fondo_6Layout.setVerticalGroup(
            JPanel_cesta_fondo_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_cesta_fondo_6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_nombre_producto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanel_cesta_fondo_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel_cesta_fondo_6Layout.createSequentialGroup()
                        .addComponent(jLabel_info_producto_seleccionado4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addComponent(jLabel_img_producto_seleccionado4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(JPanel_cesta_fondo_6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanel_cesta_fondo_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel_precio_producto)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanel_cesta_fondo_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_cantidad_productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_add_cesta4)
                .addGap(32, 32, 32))
        );

        jComboBox_otros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[nombre]", "MONOPOLY", "ADELE -21", "TRIVIAL PURSUIT", "LIVE AT RIVER PLATE - ACDC", "ABBEY ROAD - THE BEATLES", "CATAN", "PANDEMIC", "SCATTERGORIES", "HYBRID THEORY -LINKIN PARK", "ALADDIN SANE -DAVID BOWIE" }));

        jLabel_departamentos1.setForeground(new java.awt.Color(90, 91, 92));
        jLabel_departamentos1.setText("Material de oficina");

        jLabel_departamentos2.setForeground(new java.awt.Color(90, 91, 92));
        jLabel_departamentos2.setText("Otros");

        jLabel_departamentos3.setForeground(new java.awt.Color(90, 91, 92));
        jLabel_departamentos3.setText("Libros");

        jButton_borrar_cesta.setBackground(new java.awt.Color(140, 154, 158));
        jButton_borrar_cesta.setForeground(new java.awt.Color(250, 250, 255));
        jButton_borrar_cesta.setText("Borrar Cesta");
        jButton_borrar_cesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_borrar_cestajButton_librosMouseEntered(evt);
            }
        });
        jButton_borrar_cesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_borrar_cestaActionPerformed(evt);
            }
        });

        jButton_buscar_mat_oficina.setBackground(new java.awt.Color(140, 154, 158));
        jButton_buscar_mat_oficina.setForeground(new java.awt.Color(250, 250, 255));
        jButton_buscar_mat_oficina.setText("Buscar");
        jButton_buscar_mat_oficina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_buscar_mat_oficinajButton_librosMouseEntered(evt);
            }
        });
        jButton_buscar_mat_oficina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscar_mat_oficinaActionPerformed(evt);
            }
        });

        jButton_buscar_otros.setBackground(new java.awt.Color(140, 154, 158));
        jButton_buscar_otros.setForeground(new java.awt.Color(250, 250, 255));
        jButton_buscar_otros.setText("Buscar");
        jButton_buscar_otros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_buscar_otrosjButton_librosMouseEntered(evt);
            }
        });
        jButton_buscar_otros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscar_otrosActionPerformed(evt);
            }
        });

        jButton_comprar.setBackground(new java.awt.Color(140, 154, 158));
        jButton_comprar.setForeground(new java.awt.Color(250, 250, 255));
        jButton_comprar.setText("comprar");
        jButton_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_comprarborrarCesta(evt);
                jButton_comprarabrirCesta(evt);
            }
        });

        jButton_mosrtar_cesta.setBackground(new java.awt.Color(140, 154, 158));
        jButton_mosrtar_cesta.setForeground(new java.awt.Color(250, 250, 255));
        jButton_mosrtar_cesta.setText("Ver Cesta");
        jButton_mosrtar_cesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_mosrtar_cestajButton_librosMouseEntered(evt);
            }
        });
        jButton_mosrtar_cesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mosrtar_cestaActionPerformed(evt);
            }
        });

        jButton_desconectar.setBackground(new java.awt.Color(140, 154, 158));
        jButton_desconectar.setForeground(new java.awt.Color(250, 250, 255));
        jButton_desconectar.setText("Desconectarse");
        jButton_desconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_desconectarlogin(evt);
            }
        });

        javax.swing.GroupLayout jPanel_IndexLayout = new javax.swing.GroupLayout(jPanel_Index);
        jPanel_Index.setLayout(jPanel_IndexLayout);
        jPanel_IndexLayout.setHorizontalGroup(
            jPanel_IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_IndexLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel_IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_IndexLayout.createSequentialGroup()
                        .addComponent(jLabel_departamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_IndexLayout.createSequentialGroup()
                        .addGroup(jPanel_IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_IndexLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(logo_grande, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_IndexLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel_IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBox_libros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel_departamentos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jButton_buscar_libros))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel_IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_mat_oficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_departamentos1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_buscar_mat_oficina))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel_IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_otros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_departamentos2)
                                    .addComponent(jButton_buscar_otros))))
                        .addGap(83, 83, 83))))
            .addGroup(jPanel_IndexLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(jPanel_IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabel_perfil)
                    .addGroup(jPanel_IndexLayout.createSequentialGroup()
                        .addGroup(jPanel_IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_password)
                            .addComponent(jLabel_usuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_IndexLayout.createSequentialGroup()
                                .addComponent(jTextField_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanel_IndexLayout.createSequentialGroup()
                                .addComponent(jTextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_desconectar)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel_IndexLayout.createSequentialGroup()
                .addGroup(jPanel_IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_IndexLayout.createSequentialGroup()
                        .addGroup(jPanel_IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_IndexLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(JPanel_cesta_fondo_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_IndexLayout.createSequentialGroup()
                                .addGroup(jPanel_IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel_IndexLayout.createSequentialGroup()
                                        .addComponent(jButton_borrar_cesta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_IndexLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jButton_mosrtar_cesta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jLabel_total_texto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_output, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_total1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(325, 325, 325)
                                .addComponent(jButton_comprar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_IndexLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
        );
        jPanel_IndexLayout.setVerticalGroup(
            jPanel_IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_IndexLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(logo_grande, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLabel_perfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_usuario)
                    .addComponent(jTextField_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_password)
                    .addComponent(jTextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_desconectar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_departamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel_IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_departamentos1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_departamentos2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_departamentos3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_mat_oficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_libros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_otros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_buscar_libros, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_buscar_mat_oficina, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_buscar_otros, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JPanel_cesta_fondo_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_IndexLayout.createSequentialGroup()
                        .addGroup(jPanel_IndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_total_texto)
                            .addComponent(jLabel_output)
                            .addComponent(jLabel_total1)
                            .addComponent(jButton_mosrtar_cesta))
                        .addGap(23, 23, 23)
                        .addComponent(jButton_borrar_cesta))
                    .addComponent(jButton_comprar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Index, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Index, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usuarioActionPerformed
    /**
     *
     * Loggea al usuario
     *
     * @param evt
     */
    public boolean identificado = false;
    private void login(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login

        try {
            if (jTextField_usuario.getText().length() < 1 || jTextField_password.getText().length() < 1) {
                JOptionPane.showMessageDialog(null, "PONGA SUS DATOS", "ERROR", JOptionPane.ERROR_MESSAGE);
                throw new Exception("ParametrosVacios");
            }
            jTextField_usuario.setText("");
            jTextField_password.setText("");
            JOptionPane.showMessageDialog(null, "Conexión realizada  ^_^", "Login", JOptionPane.INFORMATION_MESSAGE);
            identificado = true;
            jButton_desconectar.setVisible(true);

        } catch (Exception e) {
            System.out.println("Error al hacer login");
        }


    }//GEN-LAST:event_login

    private void jButton_librosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_librosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_librosMouseEntered

    private void jButton_add_cesta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_cesta4ActionPerformed

        try {
            if (identificado) {

                String nombre_prod = jLabel_nombre_producto.getText();
                int cantidad_prod = Integer.valueOf(jTextField_cantidad_productos.getText());
                double precio_prod = Math.round(Double.valueOf(jLabel_precio_producto.getText()));
                if (nombre_prod == "[nombre]") {
                    JOptionPane.showMessageDialog(null, "SELECCIONE UN PRODUCTO", "ERROR", JOptionPane.ERROR_MESSAGE);
                    throw new Exception("NoProducto");
                }
                if (cantidad_prod <= 0) {
                    JOptionPane.showMessageDialog(null, "INSETE UNA CANTIDAD MAYOR A UNO", "ERROR", JOptionPane.ERROR_MESSAGE);
                    throw new Exception("CantProductoInvalida");
                }
                int compra = JOptionPane.showOptionDialog(null,
                        "SEGURO QUE QUIERES AÑADIR ESTO A LA CESTA???", null,
                        JOptionPane.YES_NO_OPTION, 1, null, null,
                        null);
                if (compra == 0) {
                    Arrayp.cesta.add(new Producto(nombre_prod, precio_prod, cantidad_prod));
                    jLabel_output.setText(
                            String.valueOf(
                                    Math.round(
                                            Double.valueOf(jLabel_output.getText()) + precio_prod * cantidad_prod
                                    )
                            )
                    );
                    JOptionPane.showMessageDialog(null, "PRODUCTO AÑADIDO A LA CESTA", "FELICIDADES!", JOptionPane.INFORMATION_MESSAGE);

                }
            } else {
                JOptionPane.showMessageDialog(null, "IDENTIFIQUESE PRIMERO", "ERROR", JOptionPane.ERROR_MESSAGE);
                throw new Exception("UsuarioNoLoggeado");
            }

        } catch (Exception e) {
            try {
                throw e;
            } catch (Exception ex) {
                Logger.getLogger(JFrame_index.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_jButton_add_cesta4ActionPerformed

    private void jComboBox_librosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_librosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_librosActionPerformed

    private void jButton_borrar_cestajButton_librosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_borrar_cestajButton_librosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_borrar_cestajButton_librosMouseEntered

    private void jButton_borrar_cestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_borrar_cestaActionPerformed
        if (identificado) {

            int compra = JOptionPane.showOptionDialog(null,
                    "SEGURO QUE QUIERES BORRAR LA CESTA???", null,
                    JOptionPane.YES_NO_OPTION, 1, null, null,
                    null);
            if (compra == 0) {
                Arrayp.cesta.clear();
                jLabel_output.setText("0");
                JOptionPane.showMessageDialog(null, "CESTA BORRADA", "FELICIDADES!", JOptionPane.INFORMATION_MESSAGE);

            }
        } else {
            JOptionPane.showMessageDialog(null, "IDENTIFIQUESE PRIMERO", "ERROR", JOptionPane.ERROR_MESSAGE);
            try {
                throw new Exception("UsuarioNoLoggeado");
            } catch (Exception ex) {
                Logger.getLogger(JFrame_index.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_borrar_cestaActionPerformed

    private void jButton_buscar_mat_oficinajButton_librosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_buscar_mat_oficinajButton_librosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_buscar_mat_oficinajButton_librosMouseEntered

    private void jButton_buscar_otrosjButton_librosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_buscar_otrosjButton_librosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_buscar_otrosjButton_librosMouseEntered

    private void jButton_buscar_librosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscar_librosActionPerformed
        try {
            ProductoDAOImplements p = new ProductoDAOImplements();
            jTextArea_info_producto.setText(p.mostrarInfoProducto(jComboBox_libros.getSelectedIndex(), 1));
            jLabel_nombre_producto.setText(p.mostrarNombreProducto(jComboBox_libros.getSelectedIndex(), 1));
            jLabel_precio_producto.setText(String.valueOf(p.mostrarPrecioProducto(jComboBox_libros.getSelectedIndex(), 1)));
            if (p.mostrarImaxeProducto(jComboBox_libros.getSelectedIndex(), 1) != null) {
                jLabel_img_producto_seleccionado4.setIcon(p.mostrarImaxeProducto(jComboBox_libros.getSelectedIndex(), 1));

            }
        } catch (Exception e) {
            throw e;
        }


    }//GEN-LAST:event_jButton_buscar_librosActionPerformed

    private void jButton_comprarborrarCesta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_comprarborrarCesta

        if (identificado) {

            try {
                if (Arrayp.cesta.size() < 1) {
                    JOptionPane.showMessageDialog(null, "AÑADA UN PRODUCTO A LA CESTA ANTES DE COMPRAR", "ERROR", JOptionPane.ERROR_MESSAGE);
                    throw new Exception("CestaVacia");
                }
                int compra = JOptionPane.showOptionDialog(null,
                        "SEGURO QUE QUIERES HACER LA COMPRA???", null,
                        JOptionPane.YES_NO_OPTION, 1, null, null,
                        null);
                if (compra == 0) {
                    Arrayp.cesta.clear();
                    jLabel_output.setText("0");
                    JOptionPane.showMessageDialog(null, "COMPRA REALIZADA", "FELICIDADES!", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {
                try {
                    throw e;
                } catch (Exception ex) {
                    Logger.getLogger(JFrame_index.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "IDENTIFIQUESE PRIMERO", "ERROR", JOptionPane.ERROR_MESSAGE);
            try {
                throw new Exception("UsuarioNoLoggeado");
            } catch (Exception ex) {
                Logger.getLogger(JFrame_index.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_comprarborrarCesta

    private void jButton_comprarabrirCesta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_comprarabrirCesta
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_comprarabrirCesta

    private void jTextField_cantidad_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cantidad_productosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cantidad_productosActionPerformed

    private void jButton_buscar_mat_oficinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscar_mat_oficinaActionPerformed
        try {
            ProductoDAOImplements p = new ProductoDAOImplements();
            jTextArea_info_producto.setText(p.mostrarInfoProducto(jComboBox_mat_oficina.getSelectedIndex() + 15, 2));
            jLabel_nombre_producto.setText(p.mostrarNombreProducto(jComboBox_mat_oficina.getSelectedIndex() + 15, 2));
            jLabel_precio_producto.setText(String.valueOf(p.mostrarPrecioProducto(jComboBox_mat_oficina.getSelectedIndex() + 15, 2)));
            if (p.mostrarImaxeProducto(jComboBox_libros.getSelectedIndex(), 1) != null) {
                jLabel_img_producto_seleccionado4.setIcon(p.mostrarImaxeProducto(jComboBox_libros.getSelectedIndex() + 15, 2));

            }

        } catch (Exception e) {
            throw e;
        }
    }//GEN-LAST:event_jButton_buscar_mat_oficinaActionPerformed

    private void jButton_buscar_otrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscar_otrosActionPerformed
        try {
            ProductoDAOImplements p = new ProductoDAOImplements();
            jTextArea_info_producto.setText(p.mostrarInfoProducto(jComboBox_otros.getSelectedIndex() + 25, 3));
            jLabel_nombre_producto.setText(p.mostrarNombreProducto(jComboBox_otros.getSelectedIndex() + 25, 3));
            jLabel_precio_producto.setText(String.valueOf(p.mostrarPrecioProducto(jComboBox_otros.getSelectedIndex() + 25, 3)));
            if (p.mostrarImaxeProducto(jComboBox_libros.getSelectedIndex(), 1) != null) {
                jLabel_img_producto_seleccionado4.setIcon(p.mostrarImaxeProducto(jComboBox_libros.getSelectedIndex() + 25, 3));

            }
        } catch (Exception e) {
            throw e;
        }
    }//GEN-LAST:event_jButton_buscar_otrosActionPerformed

    private void jButton_mosrtar_cestajButton_librosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_mosrtar_cestajButton_librosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_mosrtar_cestajButton_librosMouseEntered


    private void jButton_mosrtar_cestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mosrtar_cestaActionPerformed
        if (identificado) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new JFrame_cesta().setVisible(true);
                }
            });
        } else {
            JOptionPane.showMessageDialog(null, "IDENTIFIQUESE PRIMERO", "ERROR", JOptionPane.ERROR_MESSAGE);
            try {
                throw new Exception("UsuarioNoLoggeado");
            } catch (Exception ex) {
                Logger.getLogger(JFrame_index.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_mosrtar_cestaActionPerformed

    private void jButton_desconectarlogin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_desconectarlogin

        identificado = false;
        jButton_desconectar.setVisible(false);
        JOptionPane.showMessageDialog(null, "DESCONEXION EXITOSA", "FELICIDADES!", JOptionPane.INFORMATION_MESSAGE);

     }//GEN-LAST:event_jButton_desconectarlogin

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_index().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel_perfil;
    private javax.swing.JPanel JPanel_cesta_fondo_6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_add_cesta4;
    private javax.swing.JButton jButton_borrar_cesta;
    private javax.swing.JButton jButton_buscar_libros;
    private javax.swing.JButton jButton_buscar_mat_oficina;
    private javax.swing.JButton jButton_buscar_otros;
    private javax.swing.JButton jButton_comprar;
    private javax.swing.JButton jButton_desconectar;
    private javax.swing.JButton jButton_mosrtar_cesta;
    private javax.swing.JComboBox<String> jComboBox_libros;
    private javax.swing.JComboBox<String> jComboBox_mat_oficina;
    private javax.swing.JComboBox<String> jComboBox_otros;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_departamentos;
    private javax.swing.JLabel jLabel_departamentos1;
    private javax.swing.JLabel jLabel_departamentos2;
    private javax.swing.JLabel jLabel_departamentos3;
    private javax.swing.JLabel jLabel_img_producto_seleccionado4;
    private javax.swing.JLabel jLabel_info_producto_seleccionado4;
    private javax.swing.JLabel jLabel_nombre_producto;
    private javax.swing.JLabel jLabel_output;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_precio_producto;
    private javax.swing.JLabel jLabel_total1;
    private javax.swing.JLabel jLabel_total_texto;
    private javax.swing.JLabel jLabel_usuario;
    private javax.swing.JPanel jPanel_Index;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea_info_producto;
    private javax.swing.JTextField jTextField_cantidad_productos;
    private javax.swing.JPasswordField jTextField_password;
    private javax.swing.JTextField jTextField_usuario;
    private javax.swing.JLabel logo_grande;
    // End of variables declaration//GEN-END:variables
}
